"""init schema

Revision ID: ad1d11253341
Revises:
Create Date: 2026-05-21 15:34:41.099921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad1d11253341'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leetcode_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('problem_no', sa.Integer(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('statement_md', sa.Text(), nullable=False),
    sa.Column('reference_solution_md', sa.Text(), nullable=False),
    sa.Column('source_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'problem_no', name='uq_problem_cat_no'),
    sa.UniqueConstraint('source_path')
    )
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_is_core'), ['is_core'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_leetcode_id'), ['leetcode_id'], unique=False)

    op.create_table('submission',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('elapsed_sec', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('mode_limit_sec', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('review_json', sa.JSON(), nullable=True),
    sa.Column('review_rating', sa.String(length=2), nullable=True),
    sa.Column('review_can_compile', sa.Boolean(), nullable=True),
    sa.Column('user_rating_override', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_review_rating'), ['review_rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_status'), ['status'], unique=False)

    op.create_table('mastery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('auto_rating', sa.String(length=2), nullable=True),
    sa.Column('user_rating', sa.String(length=2), nullable=True),
    sa.Column('last_submission_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_submission_id'], ['submission.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id')
    )
    op.create_table('review_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('from_submission_id', sa.String(length=36), nullable=False),
    sa.Column('generated_from_rating', sa.String(length=2), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id')
    )
    with op.batch_alter_table('review_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_schedule_next_review_at'), ['next_review_at'], unique=False)

    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('t_offset_sec', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.String(length=12), nullable=False),
    sa.Column('client_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 't_offset_sec', name='uq_snapshot_sub_offset')
    )
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_submission_id'))

    op.drop_table('snapshot')
    with op.batch_alter_table('review_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_schedule_next_review_at'))

    op.drop_table('review_schedule')
    op.drop_table('mastery')
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_status'))
        batch_op.drop_index(batch_op.f('ix_submission_review_rating'))
        batch_op.drop_index(batch_op.f('ix_submission_problem_id'))

    op.drop_table('submission')
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_leetcode_id'))
        batch_op.drop_index(batch_op.f('ix_problem_is_core'))
        batch_op.drop_index(batch_op.f('ix_problem_external_id'))
        batch_op.drop_index(batch_op.f('ix_problem_category'))

    op.drop_table('problem')
    # ### end Alembic commands ###
