"""submission.parent_submission_id + snapshot.kind for continuation flow

Revision ID: d777fcacd71e
Revises: ad1d11253341
Create Date: 2026-05-22 15:24:10.293503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd777fcacd71e'
down_revision: Union[str, None] = 'ad1d11253341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLAlchemy 启动时强开 PRAGMA foreign_keys=ON(见 app/db/session.py)。
    # batch_alter_table 在 SQLite 上靠"建新表 / INSERT SELECT / DROP 旧表 / RENAME"实现,
    # 旧表 DROP 时会触发 ON DELETE CASCADE 把子表的数据连带删掉(snapshot.submission_id → submission.id)。
    # 这里在迁移期间临时关闭 FK,跑完再重新打开。SQLite 文档明确推荐此做法。
    op.execute("PRAGMA foreign_keys=OFF")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=16), server_default='code', nullable=False))

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_submission_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_submission_parent_submission_id'), ['parent_submission_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_submission_parent_submission_id',
            'submission',
            ['parent_submission_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###
    op.execute("PRAGMA foreign_keys=ON")


def downgrade() -> None:
    op.execute("PRAGMA foreign_keys=OFF")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint('fk_submission_parent_submission_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_submission_parent_submission_id'))
        batch_op.drop_column('parent_submission_id')

    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
    op.execute("PRAGMA foreign_keys=ON")
